http:
  host: banner-api
  port: 8080
  readTimeout: 5s
  writeTimeout: 10s

log_file:
  path: server.log

postgres:
  pool_max: 2

redis:
  host: redis:6379
  db: 0

shutdown_timeout: 5s