http:
  host: 127.0.0.1
  port: 8080
  readTimeout: 5s
  writeTimeout: 10s

log_file:
  path: server.log

postgres:
  pool_max: 2

redis:
  host: 127.0.0.1:6379
  db: 0

shutdown_timeout: 5s